spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/arbitrage}
    username: ${DATABASE_USERNAME:arbitrage}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
